### ISSUE TITLE
Can't refresh Partitions or tables.

### ISSUE THREAD

**Issue by ghost** [samaguire/PowerBINotebooks#16]
When I use this code it works great to refresh a dataset. But when I try to use the lines of code to refresh a particular table or partition.... it still seems to refresh the entire dataset. Here is the code I am referring to. Any help is greatly appreciated.

`
$type = "Full"                      # full, clearValues, calculate, dataOnly, [automatic], defragment
$commitMode = "transactional"        # [transactional], partialBatch
$maxParallelism = $null             # [10]
$retryCount = $null                 # [0]
$applyRefreshPolicy = "false"       # [true], false

$effectiveDate = $currentDateTime   # uses current server date time (UTC+0) unless specified

$objects = @"
    {  
      "refresh": {  
        "type": "Full",  
        "objects": [  
          {  
                "database": "$datasetName",  
                "table": "DIM_I_Item_Type_CAT",
                "partition": "DIM_I_Item_Type_CAT-398f922b-f0c1-45b4-b4fa-14123c127f38"
          }  
        ]  
      }  
    }  
"@                                 

###############Creates the paylod used in the API call to the service.

#!pwsh

$json =  [pscustomobject]@{}

if ($type) {
    $json | Add-Member -NotePropertyMembers @{type = $type}
}
if ($commitMode) {
    $json | Add-Member -NotePropertyMembers @{commitMode = $commitMode}
}
if ($maxParallelism) {
    $json | Add-Member -NotePropertyMembers @{maxParallelism = $maxParallelism}
}
if ($retryCount) {
    $json | Add-Member -NotePropertyMembers @{retryCount = $retryCount}
}
if ($applyRefreshPolicy) {
    $json | Add-Member -NotePropertyMembers @{applyRefreshPolicy = $applyRefreshPolicy}
}
if ($effectiveDate) {
    $json | Add-Member -NotePropertyMembers @{effectiveDate = $effectiveDate}
}
if ($objects) {
    $json | Add-Member -NotePropertyMembers @{objects = (ConvertFrom-Json $objects).refresh.objects | Select-Object * -ExcludeProperty "database"} -Force
}

$bodyJson = ConvertTo-Json $json
$bodyJson`

**Comment by samaguire** [comment]
It's a little tricky to say why it **seems** to not work for you, but there a couple things we can look at. Could you confirm:

1. You meet the requirements for refreshing like this (https://learn.microsoft.com/en-us/power-bi/connect-data/asynchronous-refresh#requirements), in particular is the dataset is running on premium?
2. If the dataset is backed by premium; what is the output for the step "Create payload"? It should look similar to:
``` json
{
  "type": "full",
  "commitMode": "transactional",
  "applyRefreshPolicy": "false",
  "effectiveDate": "2022-10-21T14:52:29.854980Z",
  "objects": {
    "table": "Table1",
    "partition": "Table1-0d2da98d-6fbf-4b2c-a97c-14e932a23fb6"
  }
}
```

**Comment by ghost** [comment]
thank you for your response. Yes I am on a P1 node (premium capacity). I've successfully  triggered the refresh for the whole dataset using a service principal account. It is just weird that I can't trigger a refresh on just 1 table or 1 partition. When I try, it still triggers a refresh on the whole dataset. Here is the payload:

{
    "type":  "Full",
    "commitMode":  "transactional",
    "applyRefreshPolicy":  "false",
    "effectiveDate":  "2022-10-21T08:59:32.385848Z",
    "objects":  {
                    "table":  "DIM_I_Item_Type_CAT",
                    "partition":  "DIM_I_Item_Type_CAT-398f922b-f0c1-45b4-b4fa-14123c127f38"
                }
}

When I then run these lines It triggers the refresh:

Invoke-PowerBIRestMethod -Url "$($groupUrlPart)datasets/$datasetId/refreshes" -Method Post -Body $bodyJson -ContentType "application/json"
$requestId = (Invoke-PowerBIRestMethod -Url "$($groupUrlPart)datasets/$datasetId/refreshes?`$top=1" -Method Get | ConvertFrom-Json).value.requestId


Then I run this to see the status:

$requestId = (Invoke-PowerBIRestMethod -Url "$($groupUrlPart)datasets/$datasetId/refreshes?`$top=1" -Method Get | ConvertFrom-Json).value.requestId
$body = Invoke-PowerBIRestMethod -Url "$($groupUrlPart)datasets/$datasetId/refreshes/$requestId" -Method Get | ConvertFrom-Json
$body | Select-Object * -ExcludeProperty "objects"
$body.objects | Where-Object -Property status -NE "Completed"


It shows me a LIST of all my tables in the dataset and say "in progress" for all of them: here is an example of some of the response:

table     : MAST_Currency_CD
partition : MAST_Currency_CD-697675b4-2d7d-4bc1-acad-c9affc8da32a
status    : InProgress

table     : MAST_SRC_System
partition : MAST_SRC_System-84de92dd-12df-4e0d-b64b-0e5fc3745392
status    : InProgress

table     : Dynamic Title Measures
partition : Dynamic Title Measures-37d90430-1f82-44ea-b096-a964c5de8ca1
status    : InProgress

table     : MISC Measures
partition : MISC Measures-7dc31ad7-13c1-47c6-ab8d-cbedb4a91a37
status    : InProgress

**Comment by samaguire** [comment]
I'm not sure why it Isn't working for you. The payload structure is correct, and it works for me when I do it (which I've just done right now). Are you able to refresh a single partition using another tool? SSMS or TE3?

The only other things I can think of are to check the XMLA endpoint setting so they are read/write, setting the dataset to large format mode and checking the account executing the command has read/write access on the dataset (i.e a workspace admin).

Hopefully, this helps? I'd be curious to hear back why you're not able to selectively refresh.

**Comment by ghost** [comment]
I think I found the problem (yes I can refresh partitions from tabular editor). I also got it to work when I simplify the code. When I inject the payload it does not have "square brackets in the payload". so the wrong payload currently looks like this:
{
"type": "Full",
"commitMode": "transactional",
"applyRefreshPolicy": "false",
"effectiveDate": "2022-10-21T08:59:32.385848Z",
"objects": {
"table": "DIM_I_Item_Type_CAT",
"partition": "DIM_I_Item_Type_CAT-398f922b-f0c1-45b4-b4fa-14123c127f38"
}
}

It needs to look likes this below from my understanding (notice the square brackets). When I do this it works:

{
"type": "Full",
"commitMode": "transactional",
"applyRefreshPolicy": "false",
"effectiveDate": "2022-10-21T08:59:32.385848Z",
"objects": [  #############NOTICE THE QUARE BRACKETS HERE##############################
{
"table": "DIM_I_Item_Type_CAT",
"partition": "DIM_I_Item_Type_CAT-398f922b-f0c1-45b4-b4fa-14123c127f38"
}
]  ##############AND HERE####################
}

I don't know how to inject the square brackets into the pay load? Can you help with this? Here is what needs to be updated to include the "Square" brackets:

$currentDateTime = (Get-Date -Format yyyy-MM-ddTHH:mm:ss.ffffffZ).ToString() # current local date time as if it was timezone UTC+0, which is the timezone used by Power BI Service

$type = "Full"                      # full, clearValues, calculate, dataOnly, [automatic], defragment
$commitMode = "transactional"        # [transactional], partialBatch
$maxParallelism = $null             # [10]
$retryCount = $null                 # [0]
$applyRefreshPolicy = "false"       # [true], false

$effectiveDate = $currentDateTime   # uses current server date time (UTC+0) unless specified

$objects = @"
    {  
      "refresh": {  
        "type": "Full",  
        "objects": [  
          {  
                "database": "$datasetName",  
                "table": "DIM_I_Item_Type_CAT",
                "partition": "DIM_I_Item_Type_CAT-398f922b-f0c1-45b4-b4fa-14123c127f38"
          }  
        ]  
      }  
    }  
"@     

$json =  [pscustomobject]@{}

if ($type) {
    $json | Add-Member -NotePropertyMembers @{type = $type}
}
if ($commitMode) {
    $json | Add-Member -NotePropertyMembers @{commitMode = $commitMode}
}
if ($maxParallelism) {
    $json | Add-Member -NotePropertyMembers @{maxParallelism = $maxParallelism}
}
if ($retryCount) {
    $json | Add-Member -NotePropertyMembers @{retryCount = $retryCount}
}
if ($applyRefreshPolicy) {
    $json | Add-Member -NotePropertyMembers @{applyRefreshPolicy = $applyRefreshPolicy}
}
if ($effectiveDate) {
    $json | Add-Member -NotePropertyMembers @{effectiveDate = $effectiveDate}
}
if ($objects) {
    $json | Add-Member -NotePropertyMembers @{objects = (ConvertFrom-Json $objects).refresh.objects | Select-Object * -ExcludeProperty "database"} -Force
}

$bodyJson = ConvertTo-Json $json
$bodyJson

**Comment by samaguire** [comment]
Thanks for reporting this! 👍

I've fixed the code to force the return of an array of objects rather than an object when there is only one table. Upon checking, this is correct behaviour in the docs and in line with what you've identified. I'm surprised it worked for me without this change🤷

**Comment by ghost** [comment]
Really appreciate your help. As you suggest it works perfect now. Thank you
