### ISSUE TITLE
The redirect URI 'urn:ietf:wg:oauth:2.0:oob' specified in the request does not match the redirect URIs configured for the application 

### ISSUE THREAD

**Issue by lbendlin** [samaguire/PowerBINotebooks#22]
Trying to execute Connect-PowerBIServiceAccount.

AADSTS50011: The redirect URI 'urn:ietf:wg:oauth:2.0:oob' specified in the request does not match the redirect URIs configured for the application 'xxx'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

**Comment by samaguire** [comment]
Looks like an error with the PowerShell CmdLet "Connect-PowerBIServiceAccount".

Perhaps it's just a transient issue with MS? (Which I wouldn't be able to help with) Or, perhaps related a using Power BI on a specific environment? If so, you could adjust the notebook to also pass this detail through while connecting. i.e. "Connect-PowerBIServiceAccount" would become "Connect-PowerBIServiceAccount -Environment USGov". If this fixes it, I'll look at updating the Notebook to accommodate this.

***@***.***

Regards
Stephen

From: lbendlin ***@***.***>
Sent: Friday, May 19, 2023 1:24 AM
To: samaguire/PowerBINotebooks ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [samaguire/PowerBINotebooks] The redirect URI 'urn:ietf:wg:oauth:2.0:oob' specified in the request does not match the redirect URIs configured for the application (Issue #22)


Trying to execute Connect-PowerBIServiceAccount.

AADSTS50011: The redirect URI 'urn:ietf:wg:oauth:2.0:oob' specified in the request does not match the redirect URIs configured for the application 'xxx'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

-

**Comment by lbendlin** [comment]
It seems to be an issue with Powershell 7.3.4 - same command works fine in the legacy Powershell (via ISE). Would you recommend using a different version?

**Comment by samaguire** [comment]
That's the version of PowerShell I have installed.

Can you confirm the version of the CmdLets installed when you run the NoteBook?

***@***.***


Regards
Stephen

**Comment by lbendlin** [comment]
Get-Module -Name MicrosoftPowerBIMgmt -ListAvailable
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.2.1111   MicrosoftPowerBIMgmt

Feel free to close the issue - seems unrelated to the notebooks.

**Comment by samaguire** [comment]
That is the same version. I'll close the ticket.

![image](https://github.com/samaguire/PowerBINotebooks/assets/62320770/be440aca-a948-4c38-96c8-a38afac94dff)
